apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2022-09-16T17:26:37Z"
    labels:
      app: shopping-deploy
    name: shopping-deploy
    namespace: shopping
    resourceVersion: "17304"
    uid: 510dfc12-d5e1-4e33-85f9-b1ce2509cad2
  spec:
    clusterIP: 10.107.98.104
    clusterIPs:
    - 10.107.98.104
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
    selector:
      app: shopping
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
