apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: shopping-deploy
  name: shopping-deploy
  namespace: shopping
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: shopping
    version: v1.0
  type: NodePort
status:
  loadBalancer: {}
